"""empty message

Revision ID: 000193ab81d0
Revises: 09c7d7b93f6c
Create Date: 2024-05-06 16:44:19.256277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000193ab81d0'
down_revision = '09c7d7b93f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strain_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strain_table', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
