"""empty message

Revision ID: 09c7d7b93f6c
Revises: e24a05fd1631
Create Date: 2024-05-02 14:28:32.788310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c7d7b93f6c'
down_revision = 'e24a05fd1631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strain_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strain_table', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
