"""empty message

Revision ID: 0bbefef87dce
Revises: 5a216f598087
Create Date: 2024-01-16 18:29:20.685449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bbefef87dce'
down_revision = '5a216f598087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_cart_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strain_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_favorite_cart_table_strain_id_strain_table'), 'strain_table', ['strain_id'], ['id'])

    with op.batch_alter_table('shopping_cart_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strain_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_shopping_cart_table_strain_id_strain_table'), 'strain_table', ['strain_id'], ['id'])

    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('shopping_cart_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shopping_cart_table_strain_id_strain_table'), type_='foreignkey')
        batch_op.drop_column('strain_id')

    with op.batch_alter_table('favorite_cart_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_favorite_cart_table_strain_id_strain_table'), type_='foreignkey')
        batch_op.drop_column('strain_id')

    # ### end Alembic commands ###
