"""empty message

Revision ID: 31a7f0036aaf
Revises: 
Create Date: 2024-05-13 15:32:08.209872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a7f0036aaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('juice_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collab', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('flavor', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users_table.id'], name=op.f('fk_juice_table_owner_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strain_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('aroma', sa.String(), nullable=False),
    sa.Column('taste', sa.String(), nullable=False),
    sa.Column('thc_level', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users_table.id'], name=op.f('fk_strain_table_owner_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_cart_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('juice_id', sa.Integer(), nullable=False),
    sa.Column('strain_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['juice_id'], ['juice_table.id'], name=op.f('fk_favorite_cart_table_juice_id_juice_table')),
    sa.ForeignKeyConstraint(['strain_id'], ['strain_table.id'], name=op.f('fk_favorite_cart_table_strain_id_strain_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_favorite_cart_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_cart_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('juice_id', sa.Integer(), nullable=False),
    sa.Column('strain_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['juice_id'], ['juice_table.id'], name=op.f('fk_shopping_cart_table_juice_id_juice_table')),
    sa.ForeignKeyConstraint(['strain_id'], ['strain_table.id'], name=op.f('fk_shopping_cart_table_strain_id_strain_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_shopping_cart_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_cart_table')
    op.drop_table('favorite_cart_table')
    op.drop_table('strain_table')
    op.drop_table('juice_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
