"""empty message

Revision ID: 5a216f598087
Revises: 2bedfa7e58fc
Create Date: 2024-01-11 16:09:05.512799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a216f598087'
down_revision = '2bedfa7e58fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strain_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taste', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strain_table', schema=None) as batch_op:
        batch_op.drop_column('taste')

    # ### end Alembic commands ###
