"""empty message

Revision ID: 6904a515acaf
Revises: 0bbefef87dce
Create Date: 2024-01-16 23:16:23.192704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6904a515acaf'
down_revision = '0bbefef87dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
