"""empty message

Revision ID: e24a05fd1631
Revises: 2cc6c7e496ad
Create Date: 2024-05-02 14:16:42.142947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24a05fd1631'
down_revision = '2cc6c7e496ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('juice_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('juice_table', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
